name: Windows Virtual Desktop (Tailscale)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar e Instalar Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup.exe" -OutFile ".\tailscale-setup.exe"
          Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/quiet" -Wait

      - name: Conectar ao Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTHKEY

      - name: Habilitar Área de Trabalho Remota (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Criar/Atualizar utilizador para acesso
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          net user RunnerAdmin $env:RDP_PASSWORD

      - name: Manter a VM ativa
        run: |
          while ($true) { Start-Sleep -Seconds 60 }
          
